### ISSUE TITLE
Group Sensors

### ISSUE THREAD

**Issue by Oxxl2Rock** [avollkopf/cbpi4-GroupedActor#1]
Hi, 

could you add the possibility to group sensors like it is in cbpi3 plugin?

**Comment by avollkopf** [comment]
I don't know the plugin. Do you have a link? Anyhow, a new plugin would be required.

**Comment by Oxxl2Rock** [comment]
Here's the Link of the cbpi3 Plugin 

https://github.com/IndyJoeA/cbpi_Groups

**Comment by avollkopf** [comment]
Just to double check -> You want to have an average value of the group? Or would it be also interesting to get a min and max of the group?

**Comment by Oxxl2Rock** [comment]
I'd like to have the average of 2 or more temperature sensors. it is not necessary to display the minimum and maximum temperature.

**Comment by avollkopf** [comment]
Plaesa have a look at this new repo: https://github.com/avollkopf/cbpi4_GroupedSensor

I will close this here as the sensor is a new plugin
